spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    hikari:
      username: sa
      password: